services:
  db-test:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: gitmesh-web
    ports:
      - 5433:5432
    networks:
      - gitmesh-bridge-test

  sqs:
    build:
      context: ../scripts/scaffold/sqs
    ports:
      - 9325:9324
      - 9326:9325
    networks:
      - gitmesh-bridge-test

  open-search-test:
    image: opensearchproject/opensearch:3.4.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9200
      - 9601:9600
    networks:
      - gitmesh-bridge-test

  redis-test:
    image: redis
    ports:
      - 6380:6379
    networks:
      - gitmesh-bridge-test

  temporal-test:
    build:
      context: ../scripts/scaffold/temporal
    restart: always
    ports:
      - '7234:7233'
      - '8234:8233'
    networks:
      - gitmesh-bridge-test

networks:
  gitmesh-bridge-test:
    external: true
